### ISSUE TITLE
Installing 

### ISSUE THREAD

**Issue by angelrr7702** [liblime/LibLime-Koha#6]
I been trying to install the last release on docker container but failing. I got solr working at port 8983 but nothing appear at port 5000 .  

  Is there something missing from INSTALL file to install this web application on Ununtu 14.04?

**Comment by ctfliblime** [comment]
What appears on the console when executing the `KOHA_CONF=~/koha-dev/etc/koha-conf.xml plackup app.psgi` command?

**Comment by angelrr7702** [comment]
moving away from Liblime-koha to koho-community.org .
